name: Deploy Build Folder

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy build folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          # Deletes all existing files on gh-pages and replaces with build folder
          force_orphan: true
          # Optional: Only deploy specific files from build folder
          # destination_dir: .  # Puts build contents at root of gh-pages